// Mocks generated by Mockito 5.4.6 from annotations
// in pinboard_wizard/test/pinboard_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pinboard_wizard/src/pinboard/models/add_post_response.dart'
    as _i5;
import 'package:pinboard_wizard/src/pinboard/models/api_token_response.dart'
    as _i2;
import 'package:pinboard_wizard/src/pinboard/models/credentials.dart' as _i13;
import 'package:pinboard_wizard/src/pinboard/models/post_dates_response.dart'
    as _i4;
import 'package:pinboard_wizard/src/pinboard/models/posts_response.dart' as _i3;
import 'package:pinboard_wizard/src/pinboard/models/suggest_response.dart'
    as _i8;
import 'package:pinboard_wizard/src/pinboard/models/tags_response.dart' as _i6;
import 'package:pinboard_wizard/src/pinboard/models/update_response.dart'
    as _i9;
import 'package:pinboard_wizard/src/pinboard/models/user_secret_response.dart'
    as _i7;
import 'package:pinboard_wizard/src/pinboard/pinboard_client.dart' as _i10;
import 'package:pinboard_wizard/src/services/credentials_service.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiTokenResponse_0 extends _i1.SmartFake
    implements _i2.ApiTokenResponse {
  _FakeApiTokenResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostsResponse_1 extends _i1.SmartFake implements _i3.PostsResponse {
  _FakePostsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostDatesResponse_2 extends _i1.SmartFake
    implements _i4.PostDatesResponse {
  _FakePostDatesResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddPostResponse_3 extends _i1.SmartFake
    implements _i5.AddPostResponse {
  _FakeAddPostResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTagsResponse_4 extends _i1.SmartFake implements _i6.TagsResponse {
  _FakeTagsResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserSecretResponse_5 extends _i1.SmartFake
    implements _i7.UserSecretResponse {
  _FakeUserSecretResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSuggestResponse_6 extends _i1.SmartFake
    implements _i8.SuggestResponse {
  _FakeSuggestResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateResponse_7 extends _i1.SmartFake
    implements _i9.UpdateResponse {
  _FakeUpdateResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PinboardClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPinboardClient extends _i1.Mock implements _i10.PinboardClient {
  MockPinboardClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<bool> testAuthentication() =>
      (super.noSuchMethod(
            Invocation.method(#testAuthentication, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i2.ApiTokenResponse> getUserApiToken() =>
      (super.noSuchMethod(
            Invocation.method(#getUserApiToken, []),
            returnValue: _i11.Future<_i2.ApiTokenResponse>.value(
              _FakeApiTokenResponse_0(
                this,
                Invocation.method(#getUserApiToken, []),
              ),
            ),
          )
          as _i11.Future<_i2.ApiTokenResponse>);

  @override
  _i11.Future<_i3.PostsResponse> getPosts({
    String? tag,
    int? start,
    int? results,
    DateTime? fromdt,
    DateTime? todt,
    int? meta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {
              #tag: tag,
              #start: start,
              #results: results,
              #fromdt: fromdt,
              #todt: todt,
              #meta: meta,
            }),
            returnValue: _i11.Future<_i3.PostsResponse>.value(
              _FakePostsResponse_1(
                this,
                Invocation.method(#getPosts, [], {
                  #tag: tag,
                  #start: start,
                  #results: results,
                  #fromdt: fromdt,
                  #todt: todt,
                  #meta: meta,
                }),
              ),
            ),
          )
          as _i11.Future<_i3.PostsResponse>);

  @override
  _i11.Future<_i3.PostsResponse> getRecentPosts({String? tag, int? count}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentPosts, [], {#tag: tag, #count: count}),
            returnValue: _i11.Future<_i3.PostsResponse>.value(
              _FakePostsResponse_1(
                this,
                Invocation.method(#getRecentPosts, [], {
                  #tag: tag,
                  #count: count,
                }),
              ),
            ),
          )
          as _i11.Future<_i3.PostsResponse>);

  @override
  _i11.Future<_i4.PostDatesResponse> getPostDates({String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#getPostDates, [], {#tag: tag}),
            returnValue: _i11.Future<_i4.PostDatesResponse>.value(
              _FakePostDatesResponse_2(
                this,
                Invocation.method(#getPostDates, [], {#tag: tag}),
              ),
            ),
          )
          as _i11.Future<_i4.PostDatesResponse>);

  @override
  _i11.Future<_i3.PostsResponse> getPost({
    String? tag,
    DateTime? dt,
    String? url,
    String? meta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [], {
              #tag: tag,
              #dt: dt,
              #url: url,
              #meta: meta,
            }),
            returnValue: _i11.Future<_i3.PostsResponse>.value(
              _FakePostsResponse_1(
                this,
                Invocation.method(#getPost, [], {
                  #tag: tag,
                  #dt: dt,
                  #url: url,
                  #meta: meta,
                }),
              ),
            ),
          )
          as _i11.Future<_i3.PostsResponse>);

  @override
  _i11.Future<_i5.AddPostResponse> addPost({
    required String? url,
    required String? description,
    String? extended,
    String? tags,
    DateTime? dt,
    bool? replace,
    bool? shared,
    bool? toread,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPost, [], {
              #url: url,
              #description: description,
              #extended: extended,
              #tags: tags,
              #dt: dt,
              #replace: replace,
              #shared: shared,
              #toread: toread,
            }),
            returnValue: _i11.Future<_i5.AddPostResponse>.value(
              _FakeAddPostResponse_3(
                this,
                Invocation.method(#addPost, [], {
                  #url: url,
                  #description: description,
                  #extended: extended,
                  #tags: tags,
                  #dt: dt,
                  #replace: replace,
                  #shared: shared,
                  #toread: toread,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.AddPostResponse>);

  @override
  _i11.Future<_i5.AddPostResponse> deletePost(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [url]),
            returnValue: _i11.Future<_i5.AddPostResponse>.value(
              _FakeAddPostResponse_3(
                this,
                Invocation.method(#deletePost, [url]),
              ),
            ),
          )
          as _i11.Future<_i5.AddPostResponse>);

  @override
  _i11.Future<_i6.TagsResponse> getTags() =>
      (super.noSuchMethod(
            Invocation.method(#getTags, []),
            returnValue: _i11.Future<_i6.TagsResponse>.value(
              _FakeTagsResponse_4(this, Invocation.method(#getTags, [])),
            ),
          )
          as _i11.Future<_i6.TagsResponse>);

  @override
  _i11.Future<_i5.AddPostResponse> deleteTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [tag]),
            returnValue: _i11.Future<_i5.AddPostResponse>.value(
              _FakeAddPostResponse_3(
                this,
                Invocation.method(#deleteTag, [tag]),
              ),
            ),
          )
          as _i11.Future<_i5.AddPostResponse>);

  @override
  _i11.Future<_i5.AddPostResponse> renameTag({
    required String? oldTag,
    required String? newTag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameTag, [], {
              #oldTag: oldTag,
              #newTag: newTag,
            }),
            returnValue: _i11.Future<_i5.AddPostResponse>.value(
              _FakeAddPostResponse_3(
                this,
                Invocation.method(#renameTag, [], {
                  #oldTag: oldTag,
                  #newTag: newTag,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.AddPostResponse>);

  @override
  _i11.Future<_i7.UserSecretResponse> getUserSecret() =>
      (super.noSuchMethod(
            Invocation.method(#getUserSecret, []),
            returnValue: _i11.Future<_i7.UserSecretResponse>.value(
              _FakeUserSecretResponse_5(
                this,
                Invocation.method(#getUserSecret, []),
              ),
            ),
          )
          as _i11.Future<_i7.UserSecretResponse>);

  @override
  _i11.Future<_i8.SuggestResponse> getSuggestedTags(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedTags, [url]),
            returnValue: _i11.Future<_i8.SuggestResponse>.value(
              _FakeSuggestResponse_6(
                this,
                Invocation.method(#getSuggestedTags, [url]),
              ),
            ),
          )
          as _i11.Future<_i8.SuggestResponse>);

  @override
  _i11.Future<Map<String, dynamic>> getNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getNotes, []),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<Map<String, dynamic>> getNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNote, [noteId]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<_i9.UpdateResponse> getLastUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#getLastUpdate, []),
            returnValue: _i11.Future<_i9.UpdateResponse>.value(
              _FakeUpdateResponse_7(
                this,
                Invocation.method(#getLastUpdate, []),
              ),
            ),
          )
          as _i11.Future<_i9.UpdateResponse>);

  @override
  _i11.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CredentialsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialsService extends _i1.Mock
    implements _i12.CredentialsService {
  MockCredentialsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i13.Credentials?> getCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getCredentials, []),
            returnValue: _i11.Future<_i13.Credentials?>.value(),
          )
          as _i11.Future<_i13.Credentials?>);

  @override
  _i11.Future<void> saveCredentials(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [apiKey]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> hasCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#hasCredentials, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  bool isValidApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#isValidApiKey, [apiKey]),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}
