// Mocks generated by Mockito 5.4.6 from annotations
// in pinboard_wizard/test/github/github_auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pinboard_wizard/src/github/github_credentials_storage.dart'
    as _i2;
import 'package:pinboard_wizard/src/github/models/github_notes_config.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GitHubCredentialsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubCredentialsStorage extends _i1.Mock
    implements _i2.GitHubCredentialsStorage {
  MockGitHubCredentialsStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.GitHubNotesConfig?> readConfig() =>
      (super.noSuchMethod(
            Invocation.method(#readConfig, []),
            returnValue: _i3.Future<_i4.GitHubNotesConfig?>.value(),
          )
          as _i3.Future<_i4.GitHubNotesConfig?>);

  @override
  _i3.Future<String?> readToken() =>
      (super.noSuchMethod(
            Invocation.method(#readToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveConfig(_i4.GitHubNotesConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [config]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveAll({
    required _i4.GitHubNotesConfig? config,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [], {#config: config, #token: token}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isConfigured() =>
      (super.noSuchMethod(
            Invocation.method(#isConfigured, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearConfig() =>
      (super.noSuchMethod(
            Invocation.method(#clearConfig, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
