// Mocks generated by Mockito 5.4.6 from annotations
// in pinboard_wizard/test/pages/bookmarks/add_bookmark_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pinboard_wizard/src/ai/ai_bookmark_service.dart' as _i3;
import 'package:pinboard_wizard/src/ai/ai_settings.dart' as _i4;
import 'package:pinboard_wizard/src/ai/ai_settings_service.dart' as _i5;
import 'package:pinboard_wizard/src/ai/openai/models/bookmark_suggestions.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBookmarkSuggestions_0 extends _i1.SmartFake
    implements _i2.BookmarkSuggestions {
  _FakeBookmarkSuggestions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiServiceTestResult_1 extends _i1.SmartFake
    implements _i3.AiServiceTestResult {
  _FakeAiServiceTestResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiSettings_2 extends _i1.SmartFake implements _i4.AiSettings {
  _FakeAiSettings_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOpenAiSettings_3 extends _i1.SmartFake
    implements _i4.OpenAiSettings {
  _FakeOpenAiSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebScrapingSettings_4 extends _i1.SmartFake
    implements _i4.WebScrapingSettings {
  _FakeWebScrapingSettings_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOpenAiTestResult_5 extends _i1.SmartFake
    implements _i5.OpenAiTestResult {
  _FakeOpenAiTestResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJinaTestResult_6 extends _i1.SmartFake
    implements _i5.JinaTestResult {
  _FakeJinaTestResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiBookmarkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiBookmarkService extends _i1.Mock implements _i3.AiBookmarkService {
  MockAiBookmarkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get canUseAi =>
      (super.noSuchMethod(Invocation.getter(#canUseAi), returnValue: false)
          as bool);

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<_i2.BookmarkSuggestions> analyzeUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeUrl, [url]),
            returnValue: _i6.Future<_i2.BookmarkSuggestions>.value(
              _FakeBookmarkSuggestions_0(
                this,
                Invocation.method(#analyzeUrl, [url]),
              ),
            ),
          )
          as _i6.Future<_i2.BookmarkSuggestions>);

  @override
  bool isValidUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#isValidUrl, [url]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<_i3.AiServiceTestResult> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i6.Future<_i3.AiServiceTestResult>.value(
              _FakeAiServiceTestResult_1(
                this,
                Invocation.method(#testConnection, []),
              ),
            ),
          )
          as _i6.Future<_i3.AiServiceTestResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AiSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiSettingsService extends _i1.Mock implements _i5.AiSettingsService {
  MockAiSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AiSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeAiSettings_2(this, Invocation.getter(#settings)),
          )
          as _i4.AiSettings);

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  bool get canUseAi =>
      (super.noSuchMethod(Invocation.getter(#canUseAi), returnValue: false)
          as bool);

  @override
  _i4.OpenAiSettings get openaiSettings =>
      (super.noSuchMethod(
            Invocation.getter(#openaiSettings),
            returnValue: _FakeOpenAiSettings_3(
              this,
              Invocation.getter(#openaiSettings),
            ),
          )
          as _i4.OpenAiSettings);

  @override
  _i4.WebScrapingSettings get webScrapingSettings =>
      (super.noSuchMethod(
            Invocation.getter(#webScrapingSettings),
            returnValue: _FakeWebScrapingSettings_4(
              this,
              Invocation.getter(#webScrapingSettings),
            ),
          )
          as _i4.WebScrapingSettings);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> setAiEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAiEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setOpenAiApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#setOpenAiApiKey, [apiKey]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setJinaApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#setJinaApiKey, [apiKey]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setDescriptionMaxLength(int? length) =>
      (super.noSuchMethod(
            Invocation.method(#setDescriptionMaxLength, [length]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setMaxTags(int? maxTags) =>
      (super.noSuchMethod(
            Invocation.method(#setMaxTags, [maxTags]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearOpenAiSettings() =>
      (super.noSuchMethod(
            Invocation.method(#clearOpenAiSettings, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearWebScrapingSettings() =>
      (super.noSuchMethod(
            Invocation.method(#clearWebScrapingSettings, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllAiSettings() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllAiSettings, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> validateOpenAiApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validateOpenAiApiKey, [apiKey]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> validateJinaApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validateJinaApiKey, [apiKey]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i5.OpenAiTestResult> testOpenAiConnection(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#testOpenAiConnection, [apiKey]),
            returnValue: _i6.Future<_i5.OpenAiTestResult>.value(
              _FakeOpenAiTestResult_5(
                this,
                Invocation.method(#testOpenAiConnection, [apiKey]),
              ),
            ),
          )
          as _i6.Future<_i5.OpenAiTestResult>);

  @override
  _i6.Future<_i5.JinaTestResult> testJinaConnection(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#testJinaConnection, [apiKey]),
            returnValue: _i6.Future<_i5.JinaTestResult>.value(
              _FakeJinaTestResult_6(
                this,
                Invocation.method(#testJinaConnection, [apiKey]),
              ),
            ),
          )
          as _i6.Future<_i5.JinaTestResult>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OpenAiSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomOpenAiSettings extends _i1.Mock implements _i4.OpenAiSettings {
  MockCustomOpenAiSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get descriptionMaxLength =>
      (super.noSuchMethod(
            Invocation.getter(#descriptionMaxLength),
            returnValue: 0,
          )
          as int);

  @override
  int get maxTags =>
      (super.noSuchMethod(Invocation.getter(#maxTags), returnValue: 0) as int);

  @override
  bool get hasApiKey =>
      (super.noSuchMethod(Invocation.getter(#hasApiKey), returnValue: false)
          as bool);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);

  @override
  bool get stringify =>
      (super.noSuchMethod(Invocation.getter(#stringify), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.OpenAiSettings copyWith({
    String? apiKey,
    int? descriptionMaxLength,
    int? maxTags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #apiKey: apiKey,
              #descriptionMaxLength: descriptionMaxLength,
              #maxTags: maxTags,
            }),
            returnValue: _FakeOpenAiSettings_3(
              this,
              Invocation.method(#copyWith, [], {
                #apiKey: apiKey,
                #descriptionMaxLength: descriptionMaxLength,
                #maxTags: maxTags,
              }),
            ),
          )
          as _i4.OpenAiSettings);
}
