name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build macOS app
        run: flutter build macos --release

      - name: Create app bundle directory
        run: |
          mkdir -p release/Pinboard\ Wizard.app
          cp -R build/macos/Build/Products/Release/pinboard_wizard.app/* release/Pinboard\ Wizard.app/

      - name: Create tarball
        run: |
          cd release
          tar -czf pinboard-wizard-${{ github.event.release.tag_name }}-macos.tar.gz "Pinboard Wizard.app"

      - name: Calculate SHA256
        id: sha256
        run: |
          cd release
          echo "sha256=$(shasum -a 256 pinboard-wizard-${{ github.event.release.tag_name }}-macos.tar.gz | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Verify GitHub CLI
        run: gh --version

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} release/pinboard-wizard-${{ github.event.release.tag_name }}-macos.tar.gz --clobber

      - name: Trigger cask update workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/pinboard-wizard-${VERSION}-macos.tar.gz"

          gh api repos/RikuVan/homebrew-formulae/dispatches \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -f event_type=update-cask \
            -f client_payload[version]=$VERSION \
            -f client_payload[download_url]=$DOWNLOAD_URL
